Repository eikek/sharry, pull requests merged in 2025-03, with the labels that each got.

#1614 add 24/23/100/1000 Months validity Time
  modules/webapp/src/main/elm/Data/ValidityOptions.elm
Labels: enhancement, webui

#1632 Use gh action that can update existing releases
  .github/workflows/release.yml
Labels: chore

#1633 Fix showing qr code in mobile view
  modules/webapp/src/main/elm/Page/Alias/View.elm
  modules/webapp/src/main/elm/Page/Detail/View.elm
  modules/webapp/src/main/elm/Styles.elm
Labels: webui, fix
